symbols = ['AAPL', 'AMZN', 'GOOG', 'MSFT', 'TSLA']

query_wait_time = 5

[fields] 
"symbol" = "symbol"
"latestPrice" = "current"
"open" = "open"
"close" = "close"
"peRatio" = "p/e"
"changePercent" = "% change"
"marketCap" = "mktCap"
